name: SendIt
description: Syncs the sendit folder from S3, and runs SendIt to import the data

inputs:
  environment:
    required: true
    description: The environment tag used to identify the servers to deploy to
  app_name:
    required: true
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-session-token:
    required: false
  aws-region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.aws-region }}

    - name: Find S3 bucket by tags
      id: find-bucket
      shell: bash
      run: |
        # Find S3 bucket by tags
        ENVIRONMENT="${{ inputs.environment }}"
        APP_NAME="${{ inputs.app_name }}"

        # Fetch resources with the specified tag key and value
        BUCKET_ARN=$(aws resourcegroupstaggingapi get-resources \
          --tag-filters Key=EnvironmentName,Values=$ENVIRONMENT Key=AppName,Values=$APP_NAME Key=Type,Values=data\
          --resource-type-filters s3 \
          --query 'ResourceTagMappingList[0].ResourceARN' \
          --output text)

        if [ "$BUCKET_ARN" == "None" ]; then
          echo "Error: No bucket found with the specified tags."
          exit 1
        fi

        # Extract bucket name from ARN (arn:aws:s3:::bucket-name)
        BUCKET_NAME=$(echo $BUCKET_ARN | cut -d':' -f6)
        echo "Bucket found: $BUCKET_NAME"

        # Set the bucket name as an output
        echo "bucket-name=$BUCKET_NAME" >> $GITHUB_OUTPUT

    - uses: genesislcap/appdev-workflows/ssm-command@lukask/DCD-4500-send-it-script
      with:
        command:
          source /root/.bashrc &&
          mkdir -p /data/sendit &&
          aws s3 sync s3://${{ steps.find-bucket.outputs.bucket-name }}/sendit /data/sendit --delete --exact-timestamps &&
          chmod -R 777 /data/sendit &&
          cd /data/docker-compose &&
          docker compose run --rm -v /data/sendit:/sendit genesis_app bash -c 'source ~/.bashrc; export SCRIPT_MAX_HEAP=-Xmx8g; cd /sendit; echo y | /app/run/genesis/scripts/unix/python3/JvmRun global.genesis.environment.scripts.SendTable --all . -v' &&
          rm -rf /data/sendit
        run_on_all: false
        environment: ${{ inputs.environment }}
        app_name: ${{ inputs.app_name }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.aws-region }}
