######################################################################################
# This action publish release notes to various destinations.
#
# It is used under:
#
# - gradle-branch-workflow.yml
# - generate-release-notes.yml
#
######################################################################################

name: 'Publish release notes'
description: 'Publish release notes to various destinations'
inputs:
  repository:
    description: 'the repository to generate release versions'
    type: string
    required: true
  version:
    description: 'the version being released'
    type: string
    required: false
  release-notes-txt:
    type: string
    required: true
  release-notes-md:
    type: string
    required: true
  publish-to-jfrog:
    description: 'publish release notes to Jfrog'
    type: boolean
    required: false
    default: true
  jira-token:
    description: 'token to access the jira api'
    type: string
    required: false
  github-token:
    description: 'token to access the github api'
    type: string
    required: false
  notion-token:
    description: 'token to access the notion api'
    type: string
    required: false
  slack-web-hook:
    description: 'webhook to be publish in slack'
    type: string
    required: false

runs:
  using: "composite"
  steps:
    - name: Publish Release Notes to JFrog
      if: ${{ inputs.publish-to-jfrog }}
      run: |
        ARTIFACT="v${{ inputs.version }}.md"
        REPO_FOLDER=$(echo ${{ inputs.repository}} | sed 's/genesislcap\///g')
        jfrog rt upload ./${{ inputs.release-notes-md }} platform-release-notes/server/$REPO_FOLDER/$ARTIFACT
      shell: bash

    - name: Extract Jira tickets from changes
      run : |
        # the runner uses pipefail, so prevents grep to fail in case there are no tickets
        { grep -oE '\([A-Z]{2,5}\-[0-9]+\)' ./${{ inputs.release-notes-txt }} || test $? = 1; } | sed 's/[(,)]//g' > jira_tickets.txt
      shell: bash
    - name: Update Jira tickets with fix version
      if: ${{ inputs.jira-token }}
      run : |
        python tools/release-scripts/update_jira_fix_version.py -f ./jira_tickets.txt -u devops@genesis.global -v ${{ inputs.version }} -k ${{ inputs.jira-token }}
      shell: bash

    - name: Create Github Release
      if: ${{ inputs.github-token }}
      run: |
        find ./project/ -name "*-bin.zip" | xargs python tools/release-scripts/create_github_release.py -t ${{ inputs.github-token }} -p ${{ inputs.repository }} -n ${{ inputs.release-notes-md }} -v ${{ env.RELEASE_VERSION }} -a
      shell: bash

    - name: Create Notion Release
      if: ${{ inputs.notion-token }}
      run: |
        node tools/release-scripts/publish_to_notion.mjs -t ${{ inputs.notion-token }} -p ${{ inputs.repository }} -r ${{ inputs.release-notes-md }} -v ${{ inputs.version }}
      shell: bash

    - name: Extract release note content into variable for slack
      run : |
        echo "RELEASE_NOTES<<EOF" >> "$GITHUB_ENV"
        cat slack_release_notes.txt >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"
      shell: bash

    - name: Publish notification to slack
      if: ${{ inputs.slack-web-hook }}
      uses: bryannice/gitactions-slack-notification@2.0.0
      env:
        SLACK_INCOMING_WEBHOOK: ${{ inputs.slack-web-hook }}
        SLACK_TITLE: Version ${{ inputs.version }} of ${{ inputs.repository }} is now available!
        SLACK_MESSAGE: |
          You can find the full release notes on github <${{ github.server_url }}/${{ inputs.repository }}/releases/tag/v${{ inputs.version }}|*here*>, and on notion <https://www.notion.so/genesisglobal/Platform-Release-notes-c01eb8b67d304162b56dea45d5c14599|*here*>.
          ${{ env.RELEASE_NOTES }}
        SLACK_CHANNEL: 'platform-server-releases'
        SLACK_USERNAME: 'platform-releases'