
######################################################################################
# This action generates release notes to a given repo.
#
# It is used under:
#
# - gradle-branch-workflow.yml
# - generate-release-notes.yml
#
######################################################################################

name: 'Generate release notes'
description: 'Generates release notes for the target repository/version'
inputs:
  repository:
    description: 'the repository to generate release versions'
    required: true
  release-version:
    description: 'the version being released'
    required: true
  github-token:
    description: 'token to access the github api'
    required: true
outputs:
  release-notes-txt:
    description: "the location of the TXT file containing the release notes"
    value: release_notes.txt
  release-notes-md:
    description: "the location of the MD file containing the release notes"
    value: release_notes.md
  slack-release-notes-txt:
    description: "the location of the TXT file containing the release notes (suitable to be published on slack)"
    value: slack_release_notes.txt
  definitions:
    description: "a JSON array containing the supplementary information required to execute a db test for each repository"
    value: ${{ steps.resolve-db-test-matrix.outputs.definitions }}
runs:
  using: "composite"
  steps:
    - name: Calculate previous tag to use as release note base
      run: |
        echo "PREVIOUS_VERSION=$(python tools/release-scripts/get-previous-tag.py -v ${{ inputs.release-version }} -d $(pwd)/project)" >> $GITHUB_ENV
      shell: bash
    - name: Extract Changes from GitHub
      run: |
        python tools/release-scripts/extract_changes.py -t ${{ inputs.github-token }} -tn v${{ inputs.release-version }} -ptn ${PREVIOUS_VERSION} -r ${{ inputs.repository }}
      shell: bash
    - name: Generate Release Notes
      run: |
        python tools/release-scripts/beautify-release-notes.py
        ls
      shell: bash
