name: Deploy Genesis
description: Deploys a specific version of Genesis to a server

inputs:
  version:
    required: true
    description: The image version to deploy
  environment:
    required: true
    description: The environment tag used to identify the servers to deploy to
  config-path:
    required: true
    description: The path of the Docker Compose file and supporting configs
  migrate_db:
    description: Whether to run remap or not
    required: false
    default: "true"
  initial_deploy:
    description: Whether to initiate the DB and set all hooks be ignored and set to completed
    required: false
    default: "false"
  backup_db:
    description: Use Genesis DumpIt and copy to S3 (Should not be used in Prod)
    required: false
    default: "false"
  snapshot_rds:
    description: Whether to initiate the rds snapshot creation
    required: false
    default: "false"
  custom_env_vars:
    description: Cutom env vars that will be passed to the Docker Compose command. Provide as multiline key/value pair.
    required: false
    default: ""
  app_name:
    required: true
  ecr_registry:
    required: true
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true

runs:
  using: "composite"
  steps:
    - name: Start instance if not running
      uses: genesislcap/appdev-workflows/start-stop-instances@develop
      with:
        command: "start"
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Stop Genesis
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command: "cd /data/docker-compose && docker compose down || exit 0"
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: RDS Snapshot step
      if: inputs.snapshot_rds == 'true'
      uses: genesislcap/appdev-workflows/rds-snapshot@DCD-3464
      with:
        app_name: ${{ inputs.app_name }}
        customer: ${{ inputs.customer }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Backup DB
      if: inputs.backup_db == 'true'
      uses: genesislcap/appdev-workflows/backup-db@develop
      with:
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Sync config files
      uses: genesislcap/appdev-workflows/sync-files@develop
      with:
        local-path: ${{ inputs.config-path }}
        remote-path: "/data/docker-compose"
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Populate secrets & Docker Compose env vars
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command: |
          # Remove old lines
          sed -i '/GENESIS_VERSION/d' ~/.bashrc
          sed -i '/APP_NAME/d' ~/.bashrc
          sed -i '/AWS_ECR_REGISTRY/d' ~/.bashrc
          sed -i '/DEPLOY_ENV_VAR/d' ~/.bashrc

          echo 'export GENESIS_VERSION=${{ inputs.version }}' >> ~/.bashrc
          echo 'export APP_NAME=${{ inputs.app_name }}' >> ~/.bashrc
          echo 'export AWS_ECR_REGISTRY=${{ inputs.ecr_registry }}' >> ~/.bashrc

          echo '${{ inputs.custom_env_vars }}' | while IFS='=' read -r key value; do
            if [[ -n $key ]]; then
              printf 'export %s=%s #DEPLOY_ENV_VAR\n' $key $value >> ~/.bashrc
            fi
          done

          source /root/.bashrc
          populate_secrets

        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Initiate the DB
      if: inputs.initial_deploy == 'true'
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command:
          source /root/.bashrc &&
          cd /data/docker-compose &&
          docker compose run --rm -e GENESIS_DB_INSTALL=true genesis_app
        app_name: ${{ inputs.app_name }}
        run_on_all: false
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Run DB Migration
      if: inputs.migrate_db == 'true'
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command:
          source /root/.bashrc &&
          cd /data/docker-compose &&
          docker compose run --rm -e GENESIS_DB_UPGRADE=true genesis_app
        app_name: ${{ inputs.app_name }}
        run_on_all: false
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Start Genesis
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command:
          source /root/.bashrc &&
          cd /data/docker-compose &&
          docker compose up -d
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Prune Docker
      uses: genesislcap/appdev-workflows/ssm-command@develop
      with:
        command: docker system prune -af && docker volume prune -af
        app_name: ${{ inputs.app_name }}
        environment: ${{ inputs.environment }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
