name: Run SAST 
description: Run SAST and upload results as GH artifact

inputs:  
  working-directory:
    default: .
    required: false
  app-name:
    required: true

runs:
  using: "composite"
  steps:

    - name: Install SAST CLI      
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
          curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV

    - name: Run sast security scan (text report)   
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
      run: |
        set +e
        # --report=security is default, but added for clarity
        # --exit-code 0 => never fail the job even if findings exist
        bearer scan . --report=security --exit-code 0 | tee sast-report-${{ inputs.app-name }}-${{ github.run_number }}.sarif
        set -e


    - name: Upload sast Security Report     
      uses: actions/upload-artifact@v4        
      with:
        name: sast-report-${{ inputs.app-name }}-${{ github.run_number }}
        path: sast-report-${{ inputs.app-name }}-${{ github.run_number }}.sarif

    