name: License Checker
description: Uses ORT to scan the project for the licenses of the dependencies

inputs:
  working-directory:
    required: false
    default: "."
  jfrog-username:
    required: true
  jfrog-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Copy Dependencies
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: -U -PgenesisArtifactoryUser=${{ inputs.jfrog-username }} -PgenesisArtifactoryPassword=${{ inputs.jfrog-password }}
        build-root-directory: ${{ inputs.working-directory }}/server/
        cache-disabled: true

    - name: Set Perms
      shell: bash
      run: |
        echo "genesisArtifactoryUser=${{ inputs.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
        echo "genesisArtifactoryPassword=${{ inputs.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
        mkdir ${{ github.workspace }}/ort-output

        chmod -R 777 ${{ github.workspace }}/ort-output
        chmod -R 777 ${{ inputs.working-directory }}/server/.gradle/

    - name: Run ORT Analyzer
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/server:/project \
          -v ${{ github.workspace }}/ort-output:/output \
          -v ~/.gradle/gradle.properties:~/.gradle/gradle.properties \
          ghcr.io/oss-review-toolkit/ort-minimal \
          analyze \
          -i /project \
          -o /output

    - name: Run ORT Evaluate Policy
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/ort-output:/output \
          ghcr.io/oss-review-toolkit/ort-minimal \
          evaluate-policy \
          -i /output/analyzer-result.yml \
          -o /output

    - name: Generate ORT Report
      shell: bash
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/ort-output:/output \
          ghcr.io/oss-review-toolkit/ort-minimal \
          report \
          -i /output/analyzer-result.yml \
          -o /output/report \
          -f StaticHtml

    - name: Upload ORT Report
      uses: actions/upload-artifact@v4
      with:
        name: ort-report
        path: ort-output/report
