name: RDS Snapshot Creation
description: trigger the rds db cluster snapshot process

inputs:
  snapshot-id:
    required: false
  delete-old-cluster:
    required: false
    default: "false"
  environment:
    required: true
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  app_name:
    required: true
  customer:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Find RDS Instance by tags
      id: find-rds-bytags
      shell: bash
      run: |
        # Find RDS by tags
        ENVIRONMENT="${{ inputs.environment }}"
        APP_NAME="${{ inputs.app_name }}"
        CUSTOMER="${{ inputs.customer }}"
        REGION="${{ inputs.aws-region }}"

        echo "Using filter: Key=AppName,Values=$APP_NAME Key=Customer,Values=$CUSTOMER Key=EnvironmentName,Values=$ENVIRONMENT"

        # Fetch resources with the specified tag key and value
        RDS_ARNS=$(aws resourcegroupstaggingapi get-resources \
          --region $REGION \
          --resource-type-filters rds:cluster \
          --tag-filters Key=AppName,Values=$APP_NAME Key=Customer,Values=$CUSTOMER Key=EnvironmentName,Values=$ENVIRONMENT \
          --query "ResourceTagMappingList[].ResourceARN" --region $REGION  \
          --output text | sed '/^$/d')

        echo "Found the following ARN(s). Will check and discard non-existent ones. ($RDS_ARNS)"

        for arn in $RDS_ARNS; do
          echo "Checking ARN ($arn)"
          if aws rds describe-db-clusters --db-cluster-identifier "$arn" >/dev/null 2>&1; then
            echo "ARN ($arn) exists"
            RDS_ARN=$arn
          fi
        done

        if [ "$RDS_ARN" == "None" ]; then
          echo "Error: No rds instance found with the specified tags."
          exit 1
        fi

        # Extract rds name from ARN (arn:aws:db:::cluster-id)
        CLUSTER_ID=$(echo $RDS_ARN |awk -F: '{print $NF}')
        echo "RDS DB instance found: $CLUSTER_ID"

        echo "Cluster ($CLUSTER_ID) found"

        # Set the bucket name as an output
        echo "cluster-id=$CLUSTER_ID" >> $GITHUB_OUTPUT

    - name: Get latest snapshot
      if: inputs.snapshot-id == ''
      id: find-snapshot-id
      shell: bash
      run: |
        REGION="${{ inputs.aws-region }}"

        LATEST_SNAPSHOT=$(aws rds describe-db-cluster-snapshots \
          --region $REGION \
          --db-cluster-identifier ${{ steps.find-rds-bytags.outputs.cluster-id }} \
          --snapshot-type manual \
          --query 'DBClusterSnapshots | sort_by(@, &SnapshotCreateTime)[-1].DBClusterSnapshotIdentifier' \
          --output text)

        echo "snapshot-id=$LATEST_SNAPSHOT" >> $GITHUB_OUTPUT

    - name: Checkout script
      uses: actions/checkout@v5
      with:
        repository: genesislcap/appdev-workflows
        ref: rds-snapshot
        path: "appdev-workflows"

    - name: Restore Snapshot
      shell: bash
      run: |
        cd ./appdev-workflows/restore-rds-snapshot
        python3 -m venv venv
        source venv/bin/activate
        pip3 install boto3
        python3 -u ./src/restore-db.py ${{ steps.find-rds-bytags.outputs.cluster-id }} ${{ inputs.snapshot-id || steps.find-snapshot-id.outputs.snapshot-id }} ${{ inputs.delete-old-cluster == 'true' && '--delete-old' || '' }}
