name: Scan with JFrog
description: Scan the distribution for vulnerabilities and licences

inputs:
  jfrog-username:
    required: true
  jfrog-password:
    required: true
  working-directory:
    default: .
    required: false
  server-path:
    default: server
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://genesisglobal.jfrog.io
        JF_USER: ${{ inputs.jfrog-username }}
        JF_PASSWORD: ${{ inputs.jfrog-password }}
        JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR: /opt/actions-runner/_work/_temp/_jfrog
    - name: Check if appDistZip exists
      shell: bash
      id: check_task
      working-directory: ${{ inputs.working-directory }}/${{ inputs.server-path }}/
      run: |
        if ./gradlew tasks --all -Pversion=${{ inputs.version }} -PgenesisArtifactoryUser="${{ inputs.jfrog-username }}" -PgenesisArtifactoryPassword="${{ inputs.jfrog-password }}" | grep -q "appDistZip"; then
          echo "appDistZip=true" >> $GITHUB_OUTPUT
        else
          echo "appDistZip=false" >> $GITHUB_OUTPUT
        fi

    - name: Build the dist
      if: steps.check_task.outputs.appDistZip == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}/${{ inputs.server-path }}/
      run: |
        ./gradlew appDistZip -Pversion=${{ inputs.version }} -PgenesisArtifactoryUser="${{ inputs.jfrog-username }}" -PgenesisArtifactoryPassword="${{ inputs.jfrog-password }}"

    - name: Run the JFrog scan
      env:
        JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR: /opt/actions-runner/_work/_temp/_jfrog
      if: steps.check_task.outputs.appDistZip == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}/${{ inputs.server-path }}/
      run: |
        jf s --licenses --vuln --watches "scan" */build/dist/*.zip

    - name: Append JFrog command summaries to GitHub summary
      env:
        JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR: /opt/actions-runner/_work/_temp/_jfrog
      shell: bash
      run: |
        summary_root="${JFROG_CLI_COMMAND_SUMMARY_OUTPUT_DIR}/jfrog-command-summary"
        if [ ! -d "$summary_root" ]; then
          echo "No JFrog summaries found." >> "$GITHUB_STEP_SUMMARY"
          exit 0
        fi

        for cmd_dir in "$summary_root"/*; do
          echo "$cmd_dir"
          ls -la "$cmd_dir"
          if [ -d "$cmd_dir" ]; then
            md_file="$cmd_dir/markdown.txt"
            if [ -f "$md_file" ]; then
              cmd_name=$(basename "$cmd_dir")
              echo "## JFrog Command: $cmd_name" >> "$GITHUB_STEP_SUMMARY"
              cat "$md_file" >> "$GITHUB_STEP_SUMMARY"
              echo "" >> "$GITHUB_STEP_SUMMARY"
            fi
          fi
        done
