# This is a workflow calling the steps-jobs from appdev-devops repo which has the main file
name: Gradle Build

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      repo-name:
        required: false
        type: string
      server-path:
        required: false
        type: string
        default: 'server/jvm'
      distribution_dir:
        required: false
        type: string
      product_name:
        required: true
        type: string
      version:
        required: false
        type: string
      upload:
        required: false
        type: boolean
        default: true
      build_docker:
        required: false
        default: false
        type: boolean
      java_version:
        required: false
        default: '11'
        type: string
      node_version:
        required: false
        default: '16.x'
        type: string
      use-artifactory-cache:
        type: boolean
        description: Use to the Artifactory cache
        default: false
        required: false
      push-to-artifactory-cache:
        type: boolean
        description: Push to the Artifactory cache
        default: false
        required: false
      working-directory:
        type: string
        default: .
        required: false
      server-build-gradle-arguments:
        type: string
        description: Additional arguments/properties to be passed to the server gradle build command
        required: false
      server-install-gradle-arguments:
        type: string
        description: Additional arguments/properties to be passed to the server gradle instal-* commands
        required: false
      publish-to-artifactory:
        type: boolean
        description: Publish to artifactory libs-release-local or lib-release-client
        default: false
        required: false
      cache-read-only:
        type: boolean
        description: Whether the GitHub cache should be read-only
        default: true
        required: false
      cache-write-only:
        type: boolean
        description: Whether the GitHub cache should be write-only
        default: false
        required: false
      disable-cache:
        type: boolean
        description: Whether to disable the GitHub cache entirely
        default: true
        required: false
      REGISTRY_URL:
        type: string
        description: Only used by the older version of genesisframework
        required: false
      SCOPE:
        type: string
        description: Only used by the older version of genesisframework if SCOPE is used then REGISTRY_URL has to be passed
        required: false
      sast:
        required: false
        default: true
        type: boolean
      skip-tests:
        description: "Enable TAM tag build"
        required: false
        type: boolean
        default: false
      build_server:
        description: "Whether to build and upload the server component"
        required: false
        default: true
        type: boolean
      build_web:
        description: "Whether to build and upload the web component"
        required: false
        default: true
        type: boolean

    secrets:
      GRADLE_PROPERTIES:
        required: true
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true
      GPR_READ_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: false
      JFROG_NPM_AUTH_TOKEN:
        required: false

env:
  NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}
  DISTRIBUTION_DIR: ${{ inputs.distribution_dir || format('{0}-distribution', inputs.product_name) }}
  CACHE_OPTS: ${{ inputs.disable-cache && '--no-build-cache --no-configuration-cache' || '' }}

# A workflow run is called from the devops appdev-workflow repos
jobs:
  build-server:
    if: ${{ inputs.build_server }}
    runs-on: [ appdev-selfhosted-al2023 ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Configure Node
        if: ${{ !inputs.REGISTRY_URL  }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}

      - name: Configure Node if using JFROG npm packages
        if: ${{ inputs.REGISTRY_URL }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.REGISTRY_URL }}
          scope: ${{ inputs.SCOPE }}

      - name: 'Create .npmrc'
        shell: bash
        run: |
          npm config set @genesisglobal:registry https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/
          echo "@genesisglobal:registry=https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:always-auth=true" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:always-auth=true" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:always-auth=true" >> $RUNNER_TEMP/.npmrc

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'

      - name: Login to Jfrog
        uses: docker/login-action@v3
        with:
          registry: genesisglobal-docker-remote.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          
      - name: Restore gradle.properties and setup
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        working-directory: "${{ inputs.working-directory }}"
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
          echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties

          echo "systemProp.org.gradle.internal.http.connectionTimeout=180000" >> ~/.gradle/gradle.properties
          echo "systemProp.org.gradle.internal.http.socketTimeout=180000" >> ~/.gradle/gradle.properties

          echo "dockerUrl=genesisglobal-docker-internal.jfrog.io" >> ~/.gradle/gradle.properties
          echo "dockerUsername=${{ secrets.JFROG_USERNAME }}" >> ~/.gradle/gradle.properties
          echo "dockerPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
          echo "dockerEmail=platformmanageteam@genesis.global" >> ~/.gradle/gradle.properties

          echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
          echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
          sudo chmod +x ./gradlew
          sudo chmod +x ./${{ inputs.server-path }}/gradlew
          sudo chmod -R +rx ./${{ inputs.server-path }}/
          cat ~/.gradle/gradle.properties >>  ./gradle.properties
          if [ -z "${{ inputs.repo-name }}" ]; then
            echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
          else
            echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
          fi
          RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts
          sed -E -i "s/^version=.+/version=${RELEASE_VERSION}/g" ${{ inputs.server-path }}/gradle.properties

      - name: Login to Genesis Container Registry
        uses: docker/login-action@v3
        with:
          registry: genesisglobal-docker-remote.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-overwrite-existing: true
          cache-read-only: ${{ inputs.cache-read-only }}
          cache-write-only: ${{ inputs.cache-write-only }}
          cache-disabled: ${{ inputs.disable-cache }}

      - name: Scan artifact
        uses: genesislcap/appdev-workflows/build-image/jfrog-scanning@pk/DCD-4457
        with:
          version: ${{ env.RELEASE_VERSION }}
          jfrog-username: ${{ secrets.JFROG_USERNAME }}
          jfrog-password: ${{ secrets.JFROG_PASSWORD }}
          working-directory: ${{ inputs.working-directory }}
          server-path: ${{ inputs.server-path }}
          app-name: ${{ inputs.product_name }}

      - name: Install Sast CLI
        if: inputs.sast
        working-directory: "${{ inputs.working-directory }}"
        run: |
          curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
          echo "PATH=$PWD/bin:$PATH" >> $GITHUB_ENV

      # Run scan and capture the human-readable "Security Report" into a txt file
      - name: Run sast security scan (text report)
        if: inputs.sast
        working-directory: "${{ inputs.working-directory }}"
        run: |
          set +e
          # --report=security is default, but added for clarity
          # --exit-code 0 => never fail the job even if findings exist
          bearer scan . --report=security --exit-code 0 | tee sast-report-${{ inputs.product_name }}-${{ github.run_number }}.SARIF
          set -e

      # Upload the txt report as an artifact
      - name: Upload sast Security Report
        if: inputs.sast
        uses: actions/upload-artifact@v4
        with:
          name: sast-report-${{ inputs.product_name }}-${{ github.run_number }}
          path: sast-report-${{ inputs.product_name }}-${{ github.run_number }}.SARIF

      - name: Server Build
        if: ${{ !inputs.skip-tests }}
        run: ./gradlew build --stacktrace -PpushToCache=${{ inputs.push-to-artifactory-cache }} -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }} ${{ inputs.server-build-gradle-arguments }} ${{ env.CACHE_OPTS }}
        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"
      
      - name: Server Assemble
        if: inputs.skip-tests
        run: |
          ./gradlew assemble \
            --stacktrace \
            -PpushToCache=${{ inputs.push-to-artifactory-cache }} \
            -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }} \
            ${{ inputs.server-build-gradle-arguments }} \
            ${{ env.CACHE_OPTS }}
        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"

      - name: Copy Test Reports
        working-directory: "${{ inputs.working-directory }}"
        run: |
          for dir in /opt/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ inputs.server-path }}/*/build/reports/tests/test/; do
            if [ -d "$dir" ]; then
              subfolder_name=$(echo "$dir" | sed 's/.*\/jvm\///')
              echo "Subfolder Name: $subfolder_name"
              mkdir -p "test-results/$subfolder_name"
              cp -r "$dir"/* "test-results/$subfolder_name/"
            fi
          done
        if: always()

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "${{ inputs.working-directory }}/test-results"
        if: always()

      - name: Publish All Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./**/surefire-reports/**/*.xml
            ./**/build/test-results/**/*.xml
          fail_on: nothing
          report_suite_logs: any

      - name: Docker Build Image
        if: inputs.build_docker
        run: ./gradlew :genesisproduct-${{ inputs.product_name }}:${{ inputs.product_name }}-deploy:buildImage ${{ env.CACHE_OPTS }}
        working-directory: "${{ inputs.working-directory }}/"

      - name: Docker Push Image
        if: inputs.build_docker
        run: ./gradlew :genesisproduct-${{ inputs.product_name }}:${{ inputs.product_name }}-deploy:pushImage ${{ env.CACHE_OPTS }}
        working-directory: "${{ inputs.working-directory }}/"

      - name: Create Giant Server Zip
        if: inputs.upload
        shell: bash
        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}/"
        run: |
          ./gradlew tasks | grep install- | cut -d " " -f1 | xargs -I{} ./gradlew {} ${{ inputs.server-install-gradle-arguments }}
          cd .genesis-home
          pwd
          ls -la
          tar czvf ../${{ env.DISTRIBUTION_DIR }}/build/distributions/genesis_${{ inputs.product_name }}_package-${{ env.RELEASE_VERSION }}.tar.gz *

      - name: Upload Server Package
        if: inputs.upload
        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}/${{ env.DISTRIBUTION_DIR }}/build/distributions/"
        run: |
          echo "${{ env.REPO_NAME }}"
          curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.REPO_NAME }}/server/" -T genesisproduct*.zip
          curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.REPO_NAME }}/server/" -T genesis_${{ inputs.product_name }}_package-${{ env.RELEASE_VERSION }}.tar.gz

      - name: Artifactory Publish
        if: inputs.publish-to-artifactory
        run: ./gradlew artifactoryPublish -x test -PdeployToClientRepo=false ${{ env.CACHE_OPTS }}
        working-directory: "${{ inputs.working-directory }}/${{ inputs.server-path }}"

      - name: Notify failure on Slack
        uses: youscan/gitactions-slack-notification@3.0.0
        if: failure() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ❌ Server build for ${{ inputs.product_name }} failed
          SLACK_MESSAGE: The server build for ${{ github.workflow }} failed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.REPO_NAME }}-build-notifications

      - name: Notify success on Slack
        uses: youscan/gitactions-slack-notification@3.0.0
        if: success() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ✅ Server build for ${{ inputs.product_name }} passed
          SLACK_MESSAGE: The server build for ${{ github.workflow }} passed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.REPO_NAME }}-build-notifications

  build-web:
    if: ${{ inputs.build_web }}
    runs-on: [ appdev-selfhosted-al2023 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Configure Node
        if: ${{ !inputs.REGISTRY_URL  }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}

      - name: Configure Node if using JFROG npm packages
        if: ${{ inputs.REGISTRY_URL }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: ${{ inputs.REGISTRY_URL }}
          scope: ${{ inputs.SCOPE }}

      - name: 'Create .npmrc'
        shell: bash
        run: |
          npm config set @genesisglobal:registry https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/
          echo "@genesisglobal:registry=https://genesisglobal.jfrog.io/artifactory/api/npm/npm-local/" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm-local/:always-auth=true" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/npm/:always-auth=true" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:_auth=${{secrets.JFROG_NPM_AUTH_TOKEN}}" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:email=jenkins@genesis.global" >> $RUNNER_TEMP/.npmrc
          echo "//genesisglobal.jfrog.io/artifactory/api/npm/github-packages/:always-auth=true" >> $RUNNER_TEMP/.npmrc

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'

      - name: Restore gradle.properties and setup
        working-directory: "${{ inputs.working-directory }}"
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
          echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties

          echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
          echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
          sudo chmod +x ./gradlew
          sudo chmod +x ./${{ inputs.server-path }}/gradlew

          cat ~/.gradle/gradle.properties >>  ./gradle.properties
          if [ -z "${{ inputs.repo-name }}" ]; then
            echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
          else
            echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
          fi
          RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts


      - name: Check file existence
        id: web_exists
        working-directory: "${{ inputs.working-directory }}"
        run: |
          if test -d client; then
            echo "client_folder_exists=true" >> $GITHUB_OUTPUT
            CLIENT_BUILD_LOCATION="client"
          fi
          if test -d client/web; then
            CLIENT_BUILD_LOCATION="client/web"
          fi
          echo "::set-output name=modified-location::${CLIENT_BUILD_LOCATION}"
          CLIENT_BUILD_LOCATION=$(echo "${CLIENT_BUILD_LOCATION}" | sed 's/\//:/g')
          echo "::set-output name=modified-arguments-location::${CLIENT_BUILD_LOCATION}"

      - name: Client Build
        if: steps.web_exists.outputs.client_folder_exists == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :${{ steps.web_exists.outputs.modified-arguments-location }}:assembleDist -x preCompileScripts --no-build-cache -Pversion=${{ env.RELEASE_VERSION }} -PpushToCache=${{ inputs.push-to-artifactory-cache }} -PdisableRemoteCache=${{ !inputs.use-artifactory-cache }}
          build-root-directory: "${{ inputs.working-directory }}/"
          cache-disabled: true

      - name: Upload Client Package
        if: inputs.upload &&  steps.web_exists.outputs.client_folder_exists == 'true'
        working-directory: "${{ inputs.working-directory }}/${{ steps.web_exists.outputs.modified-location }}/build/distributions"
        run: |
          mv web-distribution-${{ env.RELEASE_VERSION }}.zip ${{ env.REPO_NAME }}-web-${{ env.RELEASE_VERSION }}.zip
          curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.REPO_NAME }}/web/" -T *.zip

      - name: Notify failure on Slack
        uses: youscan/gitactions-slack-notification@3.0.0
        if: failure() && env.SLACK_INCOMING_WEBHOOK && steps.web_exists.outputs.web_exists
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ❌ Web build for ${{ inputs.product_name }} failed
          SLACK_MESSAGE: The web build for ${{ github.workflow }} failed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.REPO_NAME }}-build-notifications

      - name: Notify success on Slack
        uses: youscan/gitactions-slack-notification@3.0.0
        if: success() && env.SLACK_INCOMING_WEBHOOK && steps.web_exists.outputs.web_exists
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ✅ Web build for ${{ inputs.product_name }} passed
          SLACK_MESSAGE: The web build for ${{ github.workflow }} passed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.REPO_NAME }}-build-notifications
