# This is a workflow to being called from appdev-devops repo in genesiscicd
#  NPM web build workflow v0.0.1

name: Site Deploy

on:
  workflow_call:
    inputs:
      client:
        required: true
        type: string
      version:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      product_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
  
    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true

env:
  REPO_NAME: ${{ inputs.repo_name }}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_EMAIL: ${{secrets.JFROG_EMAIL}}
      JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
    runs-on: appdev-selfhosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          
      - name: Package + Deploy Site
        run: |
             sudo yum install zip
             cd $(pwd)/${{ inputs.repo_name }}-${{ inputs.client }}/src
             zip -r $(pwd)/${{ inputs.artifact_name }}.zip site-specific/*
             echo $(pwd)
             ls -a
             curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ inputs.repo_name }}/site/${{ inputs.client }}/${{ inputs.output }}" -T ${{ inputs.output }}.zip
