# This is a workflow calling the steps-jobs from appdev-devops repo which has the main file
name: Mono Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      product_name:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      GRADLE_PROPERTIES:
        required: true
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true
      GPR_READ_TOKEN:
        required: true 

env:
  NODE_AUTH_TOKEN: ${{secrets.GPR_READ_TOKEN}}

# A workflow run is called from the devops appdev-workflow repos
jobs:
  build:
    runs-on: [ self-hosted, selfhosted-services ]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Configure Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@genesislcap'
      
      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
          echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
          chmod +x ./gradlew
          cat ~/.gradle/gradle.properties >>  ./gradle.properties
          echo "REPO_NAME=$(echo "${{ github.event.repository.name }}" | cut -d"-" -f1)" >>  $GITHUB_ENV
          echo "VERSION=$(git tag)" >> $GITHUB_ENV
         
      - name: Server Artifactory Publish
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: build --no-build-cache -Pversion=${{ inputs.version }}
          build-root-directory: ./server/jvm
          cache-disabled: true
      
      - name: Upload Server Package
        working-directory: server/jvm/${{ inputs.product_name }}-distribution/build/distributions/
        run: |
          echo "${{ env.REPO_NAME }}" 
          curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.REPO_NAME }}/server/" -T genesisproduct*.zip
          
      - name: Client Artifactory Publish
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: :web:assembleDist --no-build-cache -Pversion=${{ inputs.version }}
          build-root-directory: ./
          cache-disabled: true

      - name: Upload Client Package
        working-directory: client/web/build/distributions
        run: |
          mv web-distribution.zip ${{ env.REPO_NAME }}-web-${{ env.VERSION }}.zip
          echo "${{ env.REPO_NAME }}"
          curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.REPO_NAME }}/web/" -T *.zip
          
