# This is a workflow calling the steps-jobs from appdev-devops repo which has the main file
name: Build RPM

on:
  workflow_call:
    inputs:
      product_name:
        required: true
        type: string
      version:
        required: true
        type: string
      artifactory_deploy_locations:
        required: true
        type: string
        description: Comma separated list of folders in Artifactory to deploy the RPM
      server-distribution:
        required: true
        type: string
        description: Server tar file
      client-distribution:
        required: true
        type: string
        description: Client tar file
      site-distribution:
        required: false
        type: string
        description: Optional site-specific override
    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_PASSWORD:
        required: true

env:
  JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}

# A workflow run is called from the devops appdev-workflow repos
jobs:
  build:
    runs-on: [ self-hosted, selfhosted-services ]
    steps:
      - name: Grab spec file
        uses: actions/checkout@v3
        with:
          repository: genesislcap/appdev-workflows
          fetch-depth: 2

      - name: Setup
        working-directory: rpm
        run: |
          sudo apt -y install rpm
          sudo apt -y install wget
          mkdir downloads
          mkdir web-downloads

      - name: Downloads
        working-directory: rpm/downloads
        run: |
          wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" https://genesisglobal.jfrog.io/artifactory/${{ inputs.server-distribution }}

      - name: Optional site download
        if: inputs.site-distribution
        working-directory: rpm/downloads
        run: |
          wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" https://genesisglobal.jfrog.io/artifactory/${{ inputs.site-distribution }}

      - name: Server Package
        working-directory: rpm/downloads
        run: |
          unzip -q genesisproduct-*.zip
          unzip -q *-site-specific-*.zip
          echo "Removing zip files"
          rm *.zip
          echo "Zipping package"
          tar -cf server-${{ inputs.version }}.tar.gz *
          mv *.tar.gz ../
          ls -al
          
      - name: Web Download and Package
        working-directory: rpm/web-downloads
        run: |
          wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" https://genesisglobal.jfrog.io/artifactory/${{ inputs.client-distribution }}
          unzip -q *web*.zip
          rm *.zip
          ls -al
          echo "Zipping package"
          tar -cf web-${{ inputs.version }}.tar.gz *
          ls -al
          mv *.tar.gz ../
          
      - name: Build RPM
        working-directory: rpm
        run: |
          ls -al
          rm -rf web-downloads downloads
          if [ -z "${{ inputs.version }}" ]; 
          then
            sed -i "s/Version://g" product.spec
            sed -i "s/1.0.0//g" product.spec
          else
            sed -i "s/1.0.0/${{ inputs.version }}/g" product.spec
          fi
          mkdir -p ~/rpmbuild/SOURCES/
          mv *.gz ~/rpmbuild/SOURCES/
          mv product.spec ~/rpmbuild/SOURCES/
          cd ~/rpmbuild/SOURCES/
          rpmbuild -bs product.spec
          
      - name: Upload RPM
        working-directory: ~/rpmbuild/SRPMS/
        run: |
          ls -al
          
      # - name: build the RPM
      #   run: |
      #     rpmbuild -bs



