# This is a workflow calling the steps-jobs from appdev-devops repo which has the main file
name: Mono Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      product_name:
        required: true
        type: string
      version:
        required: false
        type: string
      
# A workflow run is called from the devops appdev-workflow repos
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
          chmod +x ./gradlew
          cat ~/.gradle/gradle.properties >>  ./gradle.properties

      - name: Artifactory Publish
        uses: gradle/gradle-build-action@v2
        with: 
          arguments: artifactoryPublish --no-build-cache -Pversion=${{ inputs.version }}
          build-root-directory: ./server/jvm
          cache-disabled: true
