# This is a workflow to being called from appdev-devops repo in genesiscicd
#  NPM web build workflow v0.0.1

name: Site Deploy

on:
  workflow_call:
    inputs:
      client:
        required: true
        type: string
      version:
        required: true
        type: string
      product_name:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      branch:
        required: false
        type: string
      source_location:
        required: true
        type: string
    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
    runs-on: appdev-selfhosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Package + Deploy Site
        run: |
             sudo yum install zip
             cd $(pwd)/${{ inputs.source_location }}
             zip -r $(pwd)/${{ inputs.artifact_name }}.zip site-specific/*
             echo $(pwd)
             ls -a
             echo "https://genesisglobal.jfrog.io/artifactory/product/${{ inputs.product_name }}/site/${{ inputs.client }}/${{ inputs.artifact_name }}.zip"
             curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ inputs.product_name }}/site/${{ inputs.client }}/${{ inputs.artifact_name }}.zip" -T ${{ inputs.artifact_name }}.zip

      - name: Notify failure on Slack
        uses: bryannice/gitactions-slack-notification@2.0.0
        if: failure() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ❌ Site build for ${{ inputs.product_name }} failed
          SLACK_MESSAGE: The Site build for ${{ github.workflow }} failed https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
          SLACK_CHANNEL: ${{ inputs.product_name }}-build-notifications

      - name: Notify success on Slack
        uses: bryannice/gitactions-slack-notification@2.0.0
        if: success() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ✅ Site build for ${{ inputs.product_name }} passed
          SLACK_MESSAGE: The Site build for ${{ github.workflow }} passed https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_number }}
          SLACK_CHANNEL: ${{ inputs.product_name }}-build-notifications
