name:  Deploy Self serve envs

on:
  workflow_call:
    inputs:
      action:
        description: 'To deploy infra or destroy infra'
        required: true
        type: string
      file_name:
        description: 'Comma separated list of file yaml name'
        required: false
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to create resources in cddev account
    runs-on: appdev-selfhosted-al2023

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Env Set-Up
        run: |
          git checkout develop
          git pull
          sh /var/lib/cloud/scripts/per-instance/checkout-selfserve.sh
          pwd
          ls -larth
          ls -larth ~/selfserve
          rm -rf ~/selfserve/scripts/config
          mv config ~/selfserve/scripts/
          ls -larth ~/selfserve/scripts/config
          export PYTHONUNBUFFERED=TRUE
          export ANSIBLE_STDOUT_CALLBACK=debug
          python3 ~/selfserve/scripts/deployEnv.py ${{ inputs.action }} config/${{ inputs.file_name }}
