name:  Deploy Self serve envs

on:
  workflow_call:
    inputs:
      action:
        description: 'To deploy infra or destroy infra'
        required: true
        type: string
      file_name:
        description: 'Comma separated list of file yaml name'
        required: false
        type: string
      tf_branch:
        description: 'Branch name for services_tf repo'
        required: false
        default: main
        type: string
      ansible_branch:
        description: 'Branch name for services_ansible repo'
        default: master
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to create resources in cddev account
    runs-on: appdev-selfhosted-al2023

    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop

      - name: Env Set-Up
        run: |
          git checkout develop
          git pull
          echo "Checking out the required TF and ansible scripts- per run"
          /var/lib/cloud/scripts/per-instance/checkout-selfserve.sh ${{ inputs.tf_branch }} ${{ inputs.ansible_branch }}
          ls -larth
          ls -larth ~/selfserve
          rm -rf ~/selfserve/scripts/config
          mv config ~/selfserve/scripts/
          ls -larth ~/selfserve/scripts/config
          export PYTHONUNBUFFERED=TRUE
          export ANSIBLE_STDOUT_CALLBACK=debug
          python3 ~/selfserve/scripts/deployEnv.py ${{ inputs.action }} ${{ inputs.file_name }}

      - name: Extract Variables from YAML
        id: extract_vars
        run: |
          product_name=$(grep 'product_name' ~/selfserve/scripts/${{ inputs.file_name }} | head -n 1 | awk '{print $2}')
          environment_type=$(grep 'environment_type' ~/selfserve/scripts/${{ inputs.file_name }} | head -n 1 | awk '{print $2}')
          user=$(grep 'user' ~/selfserve/scripts/${{ inputs.file_name }} | head -n 1 | awk '{print $2}')
          echo "product_name=${product_name}" >> $GITHUB_ENV
          echo "environment_type=${environment_type}" >> $GITHUB_ENV
          echo "user=${user}" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-DevOps/pipelines/create_new_v2_pipelines" \
            --data-urlencode "product=${{ env.product_name }}" \
            --data-urlencode "environment_level=${{ env.environment_type }}" \
            --data-urlencode "job_name=product_${{ env.product_name }}_upgrade" \
            --data-urlencode "base_path=AppDev-CI_CD" \
            --data-urlencode "genesis_user=${{ env.user }}"