name:  Deploy Self serve envs

on:
  workflow_call:
    inputs:
      action:
        description: 'To deploy infra or destroy infra'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to create resources in cddev account
    env:
      GITTAG: ${{ github.ref_name }}
      REPO_NAME: ${{ inputs.repo_name }}
    runs-on: appdev-selfhosted
    
    steps:
      - uses: actions/checkout@v2
          
      - name: Env Set-Up
        run: |
           mv config/* ~/selfserve/scripts/
           ls -larth ~/selfserve/scripts/
           export PYTHONUNBUFFERED=TRUE
           python3 ~/selfserve/scripts/deployEnv.py ${{ inputs.action }}
