name:  Deploy Self serve envs

on:
  workflow_call:
    inputs:
      action:
        description: 'To deploy infra or destroy infra'
        required: true
        type: string
      file_name:
        description: 'Comma separated list of file yaml name'
        required: false
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to create resources in cddev account
    runs-on: appdev-selfhosted-al2023
    
    steps:
      - uses: actions/checkout@v2
          
      - name: Env Set-Up
        run: |
           mv config/* ~/selfserve/scripts/
           ls -larth ~/selfserve/scripts/
           export PYTHONUNBUFFERED=TRUE
           export ANSIBLE_STDOUT_CALLBACK=debug
           python3 ~/selfserve/scripts/deployEnv.py ${{ inputs.action }} ${{ inputs.file_name }}
