# This is a workflow to being called from appdev-devops repo in genesiscicd
#  NPM web build workflow v0.0.1

name: Site Deploy

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch:
        required: false
        type: string
      product_name:
        required: false
        type: string

    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true


env:
  REPO_NAME: ${{ inputs.repo_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to build the artifact and upload it to jfrog
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_EMAIL: ${{secrets.JFROG_EMAIL}}
      JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
    runs-on: appdev-selfhosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/checkout@v3
        with:
          repository: genesislcap/appdev-workflows
          path: ./rpm
          sparse-checkout: |
            rpm/legacy

      - name: Env Variable Setup for nightly builds off default-branch
        if: ${{ inputs.branch == 'develop' ||  inputs.branch == 'main' ||  inputs.branch == 'master' || inputs.branch == '0.0.0' }}
        run: |
              echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
              echo "PRODUCT_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)" >> $GITHUB_ENV #NOTE: only works with SSH repo urls + will cause issues with bny_investments
              echo "VERSION=${{ inputs.branch }}" >> $GITHUB_ENV
              echo "The current location is :"
              pwd
              for i in ./*
              do
                  if [ "$i" == "./snt" ]
                  then
                    WEB_VERSION=$(grep "web_version" $(find $i -name product.yml) | awk -F ':' '{print $2}' | sed 's/ //g')
                    SERVER_VERSION=$(grep server_version $(find  $i -name product.yml) |  awk -F ':' '{print $2}'| sed 's/ //g')
                  else
                    echo "$i not a client directory"
                 fi
              done
              echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-site-specific-${{ inputs.branch }}.zip" >> $GITHUB_ENV
              [[ ! -z "$WEB_VERSION" ]] && echo "WEB_VERSION=${{ inputs.branch }}" >> $GITHUB_ENV
              [[ ! -z "$SERVER_VERSION" ]] && echo "SERVER_VERSION=${{ inputs.branch }}" >> $GITHUB_ENV

      - name: Env Variable setup for auth and genesis fw versions
        run: |
             set +x -e
             curl -sSf -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -LO 'https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/server/pom-${{ env.SERVER_VERSION }}.xml'
             echo pom-${{ env.SERVER_VERSION }}.xml
             echo "AUTH_VERSION=$(echo "$(echo "$(grep -m 1 "<auth.version>" $(find . -maxdepth 1 -name pom-${{env.SERVER_VERSION}}.xml) | sed -n 's:.*<auth.version>\(.*\)</auth.version>.*:\1:p')")")" >> $GITHUB_ENV
             echo "GENESIS_VERSION=$(echo "$(echo "$(grep -m 1 "<genesis.version>" $(find . -maxdepth 1 -name pom-${{env.SERVER_VERSION}}.xml) | sed -n 's:.*<genesis.version>\(.*\)</genesis.version>.*:\1:p')")")" >> $GITHUB_ENV

      - name: Env Setup for PRODUCT_NAME for repos not following a conventions
        if: ${{ inputs.product_name }}
        run: |
              echo "PRODUCT_NAME=${{ inputs.product_name }}" >> $GITHUB_ENV #NOTE: only for those that are not following a standard naming convention

      - name: check env variables
        run: |
              echo "$(git describe --tags)"
              echo "Product Name: ${{ env.PRODUCT_NAME }}"
              echo "Version: ${{ env.VERSION }}"
              echo "Product Base: ${{ env.PRODUCT_BASE }}"
              echo "Output: ${{ env.OUTPUT }}"
              echo "SERVER_VERSION: ${{ env.SERVER_VERSION }}"
              echo "WEB_VERSION: ${{ env.WEB_VERSIOB }}"
              echo "AUTH_VERSION: ${{ env.AUTH_VERSION }}"
              echo "GENESIS_VERSION fw : ${{ env.GENESIS_VERSION }}"

      - name: Download genesis_framework, pom, server artifacts
        run: |
             set +x -e
             #download auth distribution into server_downloads folder
             mkdir distros
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}/distros" https://genesisglobal.jfrog.io/artifactory/libs-release-local/global/genesis/auth-distribution/"${{env.AUTH_VERSION}}"/auth-distribution-"${{env.AUTH_VERSION}}"-bin.zip
             #download genesis framework
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}/distros" https://genesisglobal.jfrog.io/artifactory/libs-release-local/global/genesis/genesis-distribution/"${{ env.GENESIS_VERSION }}"/genesis-distribution-"${{ env.GENESIS_VERSION }}"-bin.zip
             #download server into server_downloads folder
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}/distros"  https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/server/genesisproduct-"${{ env.PRODUCT_NAME }}"-"${{ env.SERVER_VERSION }}"-bin.zip


      - name: Package + Deploy Site per client
        run: |
             sudo yum install zip -y
             sudo yum install rpmdevtools -y
             cd ${{ env.PRODUCT_BASE }}
             echo "This is the base directory->" && echo "$(pwd)"
             for i in ./*
              do
                if [ "$i" == "./snt" ]
                then
                    CLIENT_DIR=""
                    CLIENT_NAME="genesis"
                    echo "Client directory is empty-->" && echo "$CLIENT_DIR"
                    echo "Client name is-->" && echo "$CLIENT_NAME"
                    echo "Create client specific server downloads dir for rpm creation-->" && mkdir "$CLIENT_NAME"_server_downloads
                    echo "Create client specific web downloads dir for rpm creation-->" && mkdir "$CLIENT_NAME"_web_downloads
                    echo "Change location to the client specific src directory-->" && cd ${{ env.PRODUCT_BASE }}/src

                    echo "Create artifact contaiing files from src/site-specific/ usually cfg and assembly folders"
                    zip -r ${{ env.PRODUCT_BASE }}/snt/${{ env.OUTPUT }} site-specific/*

                    echo "upload the site-specific artifac contaiing src/site-specific/* to jfrog"
                    curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/site/$CLIENT_NAME/${{env.OUTPUT}}" -T ${{ env.PRODUCT_BASE }}/snt/${{env.OUTPUT}}

                    echo "Copy this site-specific artifact to the $CLIENT_NAME_server_downloads folder"
                    cp ${{ env.PRODUCT_BASE }}/snt/${{env.OUTPUT}} ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads
                    cd ${{ env.PRODUCT_BASE }}
                    echo " Download modules into server_downloads folder in : $CLIENT_NAME_server_downloads "
                    if [[ $(grep -c "genesis_modules" ./snt/product.yml) -ge 1 ]]; then
                        set +x -e
                        echo "$(sed -e '1,/genesis_modules/d'  < ./snt/product.yml | grep "^  - { ")" > /tmp/"$CLIENT_NAME"_edited_product.yml
                        while read line
                          do
                            echo "Reading this line from product.yml now  -- $line"
                            wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads https://genesisglobal.jfrog.io/artifactory/product/$((grep -oP '(?<=name:).*?(?=,)' <<< $line)|awk '$1=$1')/server/genesisproduct-$((grep -oP '(?<=name:).*?(?=,)' <<< $line) | awk '$1=$1')-$((grep -oP '(?<=version: )[^ ]*' <<< $line)|awk '$1=$1' )-bin.zip
                          done < /tmp/"$CLIENT_NAME"_edited_product.yml
                        echo "Modules required for $CLIENT_NAME required are-->" && cat /tmp/"$CLIENT_NAME"_edited_product.yml
                        rm /tmp/"$CLIENT_NAME"_edited_product.yml
                    fi

                    echo "The present directory is -->" && echo "$(pwd)"
                    echo "The downloaded files in the client downloads directory are -->" && echo $(ls -l ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads)
                    cd ${{ env.PRODUCT_BASE }}

                    if [ "${{ env.WEB_VERSION }}" == "" ]; then

                      echo "Product Name: ${{ env.PRODUCT_NAME }} does not have a requirement for web, creating an empty zipped up folder for deployment requirements"
                      cd "$CLIENT_NAME"_web_downloads
                      echo "this is the present directory: $(pwd)"
                      echo "List of files in pwd:$(ls -a)"
                      touch temp
                      tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
                      cd ../"$CLIENT_NAME"_server_downloads
                    else
                      #download web
                      cd "$CLIENT_NAME"_web_downloads
                      echo "Product Name: ${{ env.PRODUCT_NAME }} required web to be installed ..."
                      wget --user=${{ secrets.JFROG_USERNAME }} --password="${{ secrets.JFROG_PASSWORD }}" -P ${{ env.PRODUCT_BASE }}/"$CLIENT_NAME"_web_downloads https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/web/"${{ env.PRODUCT_NAME }}"-web-"${{ env.WEB_VERSION }}".zip
                      echo "PWD after web module download-->" && echo "$(pwd)"
                      echo "List of files in present location are --> $(ls -a)"
                      unzip \*.zip
                      tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
                      cd ../"$CLIENT_NAME"_server_downloads
                    fi
                    echo "Copy all the distributions into the same location as the site-specific and the downloaded modules location"
                    cp -r ${{env.PRODUCT_BASE}}/distros/*   ${{env.PRODUCT_BASE}}/"$CLIENT_NAME"_server_downloads/
                    echo "displaying files in "$CLIENT_NAME"_server_downloads folder-->" && echo "$(ls -alrt)"
                    unzip \*.zip
                    echo "The total files after unzipping the downloaded artifacts -->"
                    rm *.zip
                    tar czvf /tmp/genesis_${{env.PRODUCT_NAME}}_package.tar.gz *
                    ls -lart /tmp/*.tar*

                    echo "Start the RPM creation process now for $CLIENT_NAME"
                    cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/pom.xml pom.xml

                    sed -i "s/PRODUCT/$PRODUCT_NAME/g" pom.xml
                    echo "pom completed"

                    if [ $(test -f /tmp/install.sh && echo 1 || echo 0) -eq 1  ]
                    then
                      rm /tmp/install.sh
                    fi
                    cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/install.sh /tmp/install.sh

                    sed -i "s/product_name/$PRODUCT_NAME/g" /tmp/install.sh
                    echo "Replace the generic users in the install script with the client user used for installation ...."
                    if [[ "$PRODUCT_NAME" == "wm_aqs" ]]
                    then
                        sed -i "s/genesisUser/aqs/g" /tmp/install.sh
                    else
                        sed -i "s/genesisUser/$(echo $PRODUCT_NAME | sed -E 's/[0-9]+//g')/g" /tmp/install.sh
                    fi
                    source ~/.bashrc
                    mvn versions:set -DnewVersion=$VERSION
                    mvn rpm:rpm
                    echo "PRODUCT NAME ${{ env.PRODUCT_NAME }}"
                    ls target/rpm/
                    cd target/rpm/genesis-${PRODUCT_NAME}/RPMS/x86_64/${RPM_NAME}
                    curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/rpm/$CLIENT_NAME/" -T *.rpm
                  else
                    echo "$i is not a directory or does not have a snt folder in it"
                  fi
              cd ${{ env.PRODUCT_BASE }}
              done
