# This is a workflow to being called from appdev-devops repo in genesiscicd
#  NPM web build workflow v0.0.1

name: Site Deploy

on:
  workflow_call:
    outputs:
        rpm_name:
          description: "The first output string"
          value: ${{ jobs.build.outputs.rpm_name }}
    inputs:
      repo_name:
        required: true
        type: string
      branch:
        required: false
        type: string
      product_name:
        required: false
        type: string
      nginx-conf:
        required: false
        type: string
        description: Optional nginx override
    secrets:
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true
      SLACK_WEBHOOK:
        required: false

env:
  REPO_NAME: ${{ inputs.repo_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      JFROG_USERNAME: ${{secrets.JFROG_USERNAME}}
      JFROG_EMAIL: ${{secrets.JFROG_EMAIL}}
      JFROG_PASSWORD: ${{secrets.JFROG_PASSWORD}}
    runs-on: appdev-selfhosted-al2023

    outputs:
      rpm_name: ${{ steps.upload-rpm.outputs.uploaded_rpm_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/checkout@v3
        with:
          repository: genesislcap/appdev-workflows
          path: ./rpm
          sparse-checkout: |
            rpm/legacy

      - name: Environment Variables
        run: |
              echo "PRODUCT_NAME=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)" >> $GITHUB_ENV #NOTE: only works with SSH repo urls + will cause issues with bny_investments
              echo "OUTPUT=$(git config --get remote.origin.url | cut -d"." -f2 | cut -d"/" -f3 | cut -d"-" -f1 | cut -d"_" -f2)-site-specific-$(git describe --tags | cut -d"_" -f2).zip" >> $GITHUB_ENV
              echo "VERSION=$(git describe --tags | cut -d"_" -f2)" >> $GITHUB_ENV
              echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
              echo "CLIENT_DIR=$([[ $(git describe --tags) = [A-Z]* ]] && echo $(ls | grep -- $(echo -$(git describe --tags | cut -d"_" -f1 | tr "[:upper:]" "[:lower:]")) | rev | cut -c 1- | rev))" >> $GITHUB_ENV
              echo "CLIENT_NAME=$([[ $(git describe --tags) = [A-Z]* ]] && echo $(ls | grep -- $(echo -$(git describe --tags | cut -d"_" -f1 | tr "[:upper:]" "[:lower:]")) | rev | cut -c 1- | rev | cut -c 1- | rev | cut -d"-" -f 1 | rev ) || echo genesis )" >> $GITHUB_ENV

      - name: Environment Variables for web and server
        run: |

              echo "WEB_VERSION=$(grep "web_version" $(find . -name product.yml) | awk -F ':' '{print $2}' | sed 's/ //g')" >> $GITHUB_ENV
              echo "SERVER_VERSION=$(grep "server_version" $(find  . -name product.yml) |  awk -F ':' '{print $2}'| sed 's/ //g')" >> $GITHUB_ENV
              echo "CLIENT_NAME=$([[ $(git describe --tags) = [A-Z]* ]] && echo $(git describe --tags | cut -d"_" -f1 | tr "[:upper:]" "[:lower:]") || echo genesis)" >> $GITHUB_ENV


      - name: Check server env var if empty set it to the tag version
        run: |
              if [ -z "${{ env.SERVER_VERSION }}" ]; then
                  echo "SERVER_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
              else
                  echo "Server version present in product.yaml"
              fi

      - name: Env Setup for PRODUCT_NAME for repos not following a conventions
        if: ${{ inputs.product_name }}
        run: |
              echo "PRODUCT_NAME=${{ inputs.product_name }}" >> $GITHUB_ENV #NOTE: only for those that are not following a standard naming convention

      - name: check env variables
        run: |
              echo "$(git describe --tags)"
              echo "Product Name: ${{ env.PRODUCT_NAME }}"
              echo "Version: ${{ env.VERSION }}"
              echo "Product Base: ${{ env.PRODUCT_BASE }}"
              echo "Output: ${{ env.OUTPUT }}"
              echo "Client Directory: ${{ env.CLIENT_DIR }}"
              echo "Client Name is : ${{ env.CLIENT_NAME }}"
              echo "Web Version: ${{ env.WEB_VERSION }}"
              echo "Server Version: ${{ env.SERVER_VERSION }}"
              if [[ -z  "${{ env.CLIENT_NAME }}" ]]
              then
                echo "Check your Tag naming convention. It should be CLIENTNAME_[a-zA-Z]-[0-9].[0-9].[0-9]"
                exit 1
              fi

      - name: Package + Deploy Site
        run: |
             sudo yum install zip
             if [ -d "${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}/src/site-specific" ]; then
                cd ${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}/src
             else
                cd ${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}
             fi
             zip -r ${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}/${{ env.OUTPUT }} site-specific/*
             echo $(pwd)
             ls -a
             curl -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -X PUT "https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/site/${{env.CLIENT_NAME}}/${{env.OUTPUT}}" -T ${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}/${{env.OUTPUT}}

      - name: Download server + assign
        run: |
             curl -sSf -u ${{ secrets.JFROG_USERNAME }}:"${{secrets.JFROG_PASSWORD}}" -LO 'https://genesisglobal.jfrog.io/artifactory/product/${{ env.PRODUCT_NAME }}/server/pom-${{ env.SERVER_VERSION }}.xml'
             echo pom-${{ env.SERVER_VERSION }}.xml
             echo "AUTH_VERSION=$(echo "$(echo "$(grep -m 1 "<auth.version>" $(find . -maxdepth 1 -name pom-${{env.SERVER_VERSION}}.xml) | sed -n 's:.*<auth.version>\(.*\)</auth.version>.*:\1:p')")")" >> $GITHUB_ENV
             echo "GENESIS_VERSION=$(echo "$(echo "$(grep -m 1 "<genesis.version>" $(find . -maxdepth 1 -name pom-${{env.SERVER_VERSION}}.xml) | sed -n 's:.*<genesis.version>\(.*\)</genesis.version>.*:\1:p')")")" >> $GITHUB_ENV

      - name: Download server, web and latest auth/genesis-distribution from JFROG
        run: |
             mkdir web_downloads
             mkdir server_downloads
             cp ${{ env.PRODUCT_BASE }}/${{ env.CLIENT_DIR }}/${{env.OUTPUT}} server_downloads
             echo "current directory: $(pwd)"
             echo "files in pwd: $(ls -a)"
             #download auth distribution into server_downloads folder
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}"/server_downloads https://genesisglobal.jfrog.io/artifactory/libs-release-local/global/genesis/auth-distribution/"${{env.AUTH_VERSION}}"/auth-distribution-"${{env.AUTH_VERSION}}"-bin.zip
             #download genesis
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}"/server_downloads https://genesisglobal.jfrog.io/artifactory/libs-release-local/global/genesis/genesis-distribution/"${{ env.GENESIS_VERSION }}"/genesis-distribution-"${{ env.GENESIS_VERSION }}"-bin.zip
             #download server into server_downloads folder
             wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}"/server_downloads https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/server/genesisproduct-"${{ env.PRODUCT_NAME }}"-"${{ env.SERVER_VERSION }}"-bin.zip
             #download modules into server_downloads folder

             if [ -d "snt" ]; then
                 cd snt
                 if [[ $(grep -c "genesis_modules" ./product.yml) -ge 1 ]]; then   echo "$(sed -e '1,/genesis_modules/d'  < ./product.yml | grep "^  - { ")" > /tmp/edited_product.yml;   while read line; do echo
                 wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" -P "${{env.PRODUCT_BASE}}"/server_downloads https://genesisglobal.jfrog.io/artifactory/product/$((grep -oP '(?<=name:).*?(?=,)' <<< $line)|awk '$1=$1')/server/genesisproduct-$((grep -oP '(?<=name:).*?(?=,)' <<< $line) | awk '$1=$1')-$((grep -oP '(?<=version: )[^ ]*' <<< $line)|awk '$1=$1' )-bin.zip ;   done < /tmp/edited_product.yml;   rm /tmp/edited_product.yml; fi
                 echo "this is the present directory: $(pwd)"
                 echo "LIST of FILES: $(ls -a)"
             fi

             if [ "${{ env.WEB_VERSION }}" == "" ]; then
               echo "Product Name: ${{ env.PRODUCT_NAME }}"
               #download web
               echo "PWD after module download: $(pwd)"
               cd ${{ env.PRODUCT_BASE }}/web_downloads
               echo "this is the present directory: $(pwd)"
               echo "List of files in pwd:$(ls -a)"
               #  unzip \*.zip
               touch temp
               if [ -n "${{ inputs.nginx-conf }}" ]; then
                 cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
               fi
               tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
               cd ../server_downloads
             else
               #download web
               echo "PWD after module download: $(pwd)"
               cd ..
               WEB_PRODUCT_NAME=$(echo "${{ env.PRODUCT_NAME }}" | cut -d"_" -f2)
               wget --user=${{ secrets.JFROG_USERNAME }} --password="${{ secrets.JFROG_PASSWORD }}" -P "${{ env.PRODUCT_BASE }}"/web_downloads https://genesisglobal.jfrog.io/artifactory/product/"${{ env.PRODUCT_NAME }}"/web/$WEB_PRODUCT_NAME-web-"${{ env.WEB_VERSION }}".zip
               cd web_downloads
               echo "this is the present directory: $(pwd)"
               echo "List of files in pwd:$(ls -a)"
               unzip -o \*.zip
               if [ -n "${{ inputs.nginx-conf }}" ]; then
                 cp "${GITHUB_WORKSPACE}/${{ inputs.nginx-conf }}" ./nginx.conf
               fi
               tar czvf /tmp/genesis_${{ env.PRODUCT_NAME }}_web.tar.gz *
               cd ../server_downloads
             fi
             echo "displaying files in server_downloads folder: $(ls -a)"
             unzip -o \*.zip
             ls
             rm *.zip
             tar czvf /tmp/genesis_${{env.PRODUCT_NAME}}_package.tar.gz *
             ls -lart /tmp/*.tar*
        env:
          JAVA_TOOL_OPTIONS: ${{'-Xmx8192m' }}

      - name: Create RPM
        run: |
            sudo yum install rpm -y
            sudo yum install rpmdevtools -y
            touch pom.xml
            rm pom.xml
            cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/pom.xml pom.xml
            sed -i "s/PRODUCT/$PRODUCT_NAME/g" pom.xml
            echo "pom completed"
            if [ $(test -f /tmp/install.sh && echo 1 || echo 0) -eq 1  ]
            then
              rm /tmp/install.sh
            fi
            echo "install.sh start"
            cp ${{ env.PRODUCT_BASE }}/rpm/rpm/legacy/install.sh /tmp/install.sh
            sed -i "s/product_name/$PRODUCT_NAME/g" /tmp/install.sh
            if [[ "$PRODUCT_NAME" == "wm_aqs" ]]
            then
                sed -i "s/genesisUser/aqs/g" /tmp/install.sh
            else
                sed -i "s/genesisUser/$(echo $PRODUCT_NAME | sed -E 's/[0-9]+//g')/g" /tmp/install.sh
            fi
            source ~/.bashrc
            mvn versions:set -DnewVersion=$VERSION
            mvn rpm:rpm

      - name: Upload RPM
        run: |
          echo "PRODUCT NAME: ${{ env.PRODUCT_NAME }}"
          echo "RPM NAME: ${{ env.RPM_NAME }}"
          ls target/rpm/
          cd target/rpm/genesis-${PRODUCT_NAME}/RPMS/x86_64
          pwd
          ls -lart
          aws s3 sync . s3://product-rpms/product/${{ env.PRODUCT_NAME }}/rpm/$CLIENT_NAME/

      - name: GET  RPM NAME
        id: upload-rpm
        run: |
          cd target/rpm/genesis-${PRODUCT_NAME}/RPMS/x86_64
          ls -al
          uploaded_rpm_name=$(ls -1 *.rpm)
          echo "$uploaded_rpm_name" > uploaded_rpm_name.txt
          echo "Uploaded RPM Name: $uploaded_rpm_name"
          echo "uploaded_rpm_name=$uploaded_rpm_name" >> $GITHUB_OUTPUT

      - name: Notify failure on Slack
        uses: bryannice/gitactions-slack-notification@2.0.0
        if: failure() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ❌ Site build for ${{ env.PRODUCT_NAME }} failed
          SLACK_MESSAGE: The Site build for ${{ github.workflow }} failed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.PRODUCT_NAME }}-build-notifications

      - name: Notify success on Slack
        uses: bryannice/gitactions-slack-notification@2.0.0
        if: success() && env.SLACK_INCOMING_WEBHOOK
        env:
          SLACK_INCOMING_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ✅ Site build for ${{ env.PRODUCT_NAME }} passed
          SLACK_MESSAGE: The Site build for ${{ github.workflow }} passed https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
          SLACK_CHANNEL: ${{ env.PRODUCT_NAME }}-build-notifications
