name: Lint Code Base

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch:
        required: false
        type: string
      linter_rules_path:
        required: true
        type: string
      css_file_name: 
        required: true
        type: string
      es_config_file: 
        required: true
        type: string
      typescript_standard_tsconfig_file:
        required: true
        type: string
      validate_jscpd:
        required: true
        type: string
        

    secrets:
      GPR_READ_TOKEN:
        required: true

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: Install ESLint Google config
        run: |
            npm install eslint-config-google --save-dev

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          LOG_LEVEL: ERROR
          LINTER_RULES_PATH: ${{ inputs.linter_rules_path }}
          CSS_FILE_NAME: ${{ inputs.css_file_name }}
          TYPESCRIPT_ES_CONFIG_FILE: ${{ inputs.es_config_file }}
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: ${{ inputs.typescript_standard_tsconfig_file }}
          VALIDATE_JSCPD: ${{ inputs.validate_jscpd }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_MARKDOWN: false
          VALIDATE_EDITORCONFIG: false
     
      - name: Lint Check
        if: always()
        run: |
          echo "LINT_CHECK=$(grep -Fxq "lint" $(cat package.json))" >> $GITHUB_ENV

      - name: NPM Lint
        run: |
            npm run lint
