name: Lint Code Base

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      branch:
        required: false
        type: string
      linter_rules_path:
        required: true
        type: string
      css_file_name: 
        default: .stylelintrc.js
        required: false
        type: string
      es_config_file: 
        default: .eslintrc.js
        required: false
        type: string
      typescript_standard_tsconfig_file:
        default: tsconfig.eslint.json
        required: false
        type: string
        
    secrets:
      GPR_READ_TOKEN:
        required: true

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
              
      - name: Install ESLint Google config
        run: |
            npm install eslint-config-google --save-dev

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: develop
          LOG_LEVEL: ERROR
          LINTER_RULES_PATH: ${{ inputs.linter_rules_path }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSS_FILE_NAME: ${{ inputs.css_file_name }}
          TYPESCRIPT_ES_CONFIG_FILE: ${{ inputs.es_config_file }}
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: ${{ inputs.typescript_standard_tsconfig_file }}
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          
          
