name: PostgreSQL Schema Restore Using Docker

on:


  workflow_call:

jobs:
  k6-test:
    name: Run k6 Load Test
    runs-on: appdev-selfhosted-al2023

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          curl -s https://api.github.com/repos/grafana/k6/releases/latest | grep "browser_download_url.*linux-amd64.rpm" | cut -d '"' -f 4
          sudo curl -L -o k6.rpm https://github.com/grafana/k6/releases/download/v0.51.0/k6-v0.51.0-linux-amd64.rpm
          sudo dnf install -y --nogpgcheck k6.rpm
      - name: Run k6 load test
        run: K6_LOG_LEVEL=error k6 run PerformanceTest/insert_latency_v1.js