name:  Refresh  Database  from Archive

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
      s3imagepath:
        required: true
        type: string
      genesis_user:
        required: false
        type: string
      branch:
        required: false
        type: string
      startserverdatetime:
        required: false
        type: string

    secrets:
      JENKINS_SECURITYTOKEN:
        required: true
      JENKINS_TOKEN:
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to refresh postgre db
    runs-on: appdev-small

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Print Input Values
        run: |
          echo "hostname: ${{ inputs.hostname }}"
          echo "s3ImagePath: ${{ inputs.s3ImagePath }}"
          echo "genesis_user: ${{ inputs.genesis_user }}"
          echo "startserverdatetime: ${{ inputs.startserverdatetime }}"

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/PLT_QA_Automation/DB_Refresh_ExistingInstance" \
            --data-urlencode "host_name=${{ inputs.HOSTNAME }}" \
            --data-urlencode "s3ImagePath=${{ inputs.s3imagepath }}" \
            --data-urlencode "genesis_user=${{ inputs.genesis_user }}" \
            --data-urlencode "account=genesisglobalcddev" \
            --data-urlencode "extra_variables=" \
            --data-urlencode "startserverdatetime=${{ inputs.startserverdatetime }}"

      - name: Install jq
        run: sudo dnf install -y jq

      - name: wait-for-completion of Jenkins  Job
        run: |
          JOB_STATUS=""
          JOB_URL="https://jenkinsdev.cdservice.genesis.global/job/AppDev-CI_CD/job/PLT_QA_Automation/job/DB_Refresh_ExistingInstance/lastBuild/api/json"

          while [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; do
            RESPONSE=$(curl -s -u "purna.sakhamuri:${{ secrets.JENKINS_TOKEN }}" "$JOB_URL")
            JOB_STATUS=$(echo "$RESPONSE" | jq -r .result)
            echo "Current status: $JOB_STATUS"

            if [ "$JOB_STATUS" == "SUCCESS" ]; then
              echo "Jenkins job completed successfully."
              exit 0
            elif [ "$JOB_STATUS" == "FAILURE" ]; then
              echo "Jenkins job failed."
              exit 1
            elif [ "$JOB_STATUS" == "ABORTED" ]; then
              echo "Jenkins job was aborted."
              exit 2
            elif [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; then
              echo "Job is still running..."
              sleep 10
            fi
          done