name:  Deploy package

on:
  workflow_call:
    inputs:     
      hostname:
        required: false
        type: string
      s3ImagePath:
        required: false
        type: string
      genesis_user:
        required: false
        type: string
      app_user:
        required: false
        type: string

      testautomation_build:
        required: false
        default: false
        type: boolean
      startserverdatetime:
        required: false
        type: string

    secrets:
      JENKINS_SECURITYTOKEN:
        required: true
      JENKINS_TOKEN:
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Steps to refresh postgre db 
    runs-on: appdev-small
    environment: master

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Print Input Values
        run: |
          echo "hostname: ${{ inputs.hostname }}"
          echo "s3ImagePath: ${{ inputs.s3ImagePath }}"
          echo "genesis_user: ${{ inputs.genesis_user }}"
          echo "startserverdatetime: ${{ inputs.startserverdatetime }}"
          echo "app_user: ${{ inputs.app_user }}"            

      - name: Install jq
        if: ${{ inputs.testautomation_build }}
        run: sudo dnf install -y jq
