name: Relase (TAG) version

on:
  workflow_call:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.JENKINSGENESIS_TOKEN }}
      
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Release
        env:
          GH_TOKEN: ${{secrets.JENKINSGENESIS_TOKEN}}
        run: |
          npm ci
          npm run release
