# This is a workflow calling the steps-jobs from appdev-devops repo which has the main file
name: Run Maven test suite

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      profile:
        required: false
        type: string
      test-root-path:
        required: true
        type: string
    secrets:
      PAGES_TOKEN:
        required: true
jobs:
  build:
    runs-on: [ appdev-selfhosted-al2023 ]
    container:
      image: mcr.microsoft.com/playwright/java:v1.35.1-jammy
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        ref: ${{ inputs.branch }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Run mvn
      shell: bash
      run: |
        MVN_OPTIONS=""
        if [ -n "${{ inputs.profile }}" ]; then
          MVN_OPTIONS="$MVN_OPTIONS -P ${{ inputs.profile }}"
        fi
        cd ${{ inputs.test-root-path }}
        mvn clean test $MVN_OPTIONS -Dbrowser=chrome-headless
    - name: Install git
      shell: bash
      run: |
        apt update
        apt install -y git
    - name: Generate Allure report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: ${{ inputs.test-root-path }}/target/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PAGES_TOKEN }}
        publish_dir:  allure-history
