---
name: SonarCloud

on:
  workflow_call:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Env Setup
        run:  |
              echo "PRODUCT_BASE=$(pwd)" >> $GITHUB_ENV
              
      - name: Env Setup
        run:  |
              ls -lart ${{ env.PRODUCT_BASE }}
              ls -lart ${{ env.PRODUCT_BASE }}/src

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=genesislcap
            -Dsonar.projectKey=${{ env.REPO_NAME }}
            -Dsonar.sources=${{ env.PRODUCT_BASE }}/src
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
          SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
