name:  Sonar Update

on:
  workflow_call:
    inputs:
      hostname:
        required: false
        type: string
      s3ImagePath:
        required: false
        type: string
      genesis_user:
        required: false
        type: string
      appuser:
        required: false
        type: string

      # testautomation_build:
      #   required: false
      #   default: false
      #   type: boolean
      # startserverdatetime:
      #   required: false
      #   type: string

    secrets:
      JENKINS_SECURITYTOKEN:
        required: true
      JENKINS_TOKEN:
        required: false
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-aws-credentials:
    runs-on: [ appdev-small ]
    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.set-creds.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.set-creds.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ steps.set-creds.outputs.AWS_SESSION_TOKEN }}

    env:
      SSM_PARAM_NAME: githubrunner-cddev-policy
      REGION: eu-west-2

    steps:

      - name: Install AWS CLI and jq
        run: |
          sudo dnf update -y
          sudo dnf install -y awscli jq
      - name: Fetch and Assume AWS Role
        id: set-creds
        run: |
          # Unset existing AWS credentials
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
          # Fetch the AWS SSM parameter containing the role ARN
          aws_ssm_param_arn=$(aws ssm get-parameter --name $SSM_PARAM_NAME --region=$REGION --with-decryption --query "Parameter.Value")
          # Assume the IAM role using STS and extract the credentials
          aws_credentials_json=$(aws sts assume-role --role-arn ${aws_ssm_param_arn//\"/} --role-session-name githubActionSession --duration 3600 --region $REGION)
          # Extract credentials and output them for the next job
          AWS_ACCESS_KEY_ID=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.AccessKeyId)
          AWS_SECRET_ACCESS_KEY=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.SecretAccessKey)
          AWS_SESSION_TOKEN=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.SessionToken)
          # Set outputs for next jobs to use
          echo "::set-output name=AWS_ACCESS_KEY_ID::$AWS_ACCESS_KEY_ID"
          echo "::set-output name=AWS_SECRET_ACCESS_KEY::$AWS_SECRET_ACCESS_KEY"
          echo "::set-output name=AWS_SESSION_TOKEN::$AWS_SESSION_TOKEN"

  build:
    name: Steps to update sonar
    runs-on: appdev-small
    environment: master

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Print Input Values
        run: |
          echo "hostname: ${{ inputs.hostname }}"
          echo "genesis_user: ${{ inputs.genesis_user }}"

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/PLT_QA_Automation/sonar-update" \
            --data-urlencode "host_name=${{ inputs.HOSTNAME }}" \
            --data-urlencode "appuser=${{ inputs.appuser }}"




      - name: Install jq
        run: sudo dnf install -y jq

      - name: Poll Jenkins for Job Status
        run: |
          JOB_STATUS=""
          JOB_URL="https://jenkinsdev.cdservice.genesis.global/job/AppDev-CI_CD/job/PLT_QA_Automation/job/sonar-update/lastBuild/api/json"

          while [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; do
            RESPONSE=$(curl -s -u "purna.sakhamuri:${{ secrets.JENKINS_TOKEN }}" "$JOB_URL")
            JOB_STATUS=$(echo "$RESPONSE" | jq -r .result)
            echo "Current status: $JOB_STATUS"

            if [ "$JOB_STATUS" == "SUCCESS" ]; then
              echo "Jenkins job completed successfully."
              exit 0
            elif [ "$JOB_STATUS" == "FAILURE" ]; then
              echo "Jenkins job failed."
              exit 1
            elif [ "$JOB_STATUS" == "ABORTED" ]; then
              echo "Jenkins job was aborted."
              exit 2
            elif [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; then
              echo "Job is still running..."
              sleep 10
            fi
          done