---
name: SonarCloud

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string

    secrets:
      JENKINSGENESIS_SONAR:
        required: true
      GPR_READ_TOKEN:
        required: true

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: appdev-selfhosted-al2023
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Env Setup
        run:  |
          echo "${{ inputs.repo_name }}"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=genesislcap
            -Dsonar.projectKey=genesislcap_${{ inputs.repo_name }}
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
          SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
