name:  Sonar Update

on:
  workflow_call:
    inputs:
      hostname:
        required: false
        type: string
      s3ImagePath:
        required: false
        type: string
      genesis_user:
        required: false
        type: string
      appuser:
        required: false
        type: string

      # testautomation_build:
      #   required: false
      #   default: false
      #   type: boolean
      # startserverdatetime:
      #   required: false
      #   type: string

      branch:
        required: false
        type: string
      version:
        required: false
        type: string
      server-path:
        required: false
        type: string
        default: 'server/jvm'
      java_version:
        required: false
        default: '11'
        type: string
      node_version:
        required: false
        default: '16.x'
        type: string
      REGISTRY_URL:
        type: string
        description: Only used by the older version of genesisframework
        required: false
      SCOPE:
        type: string
        description: Only used by the older version of genesisframework if SCOPE is used then REGISTRY_URL has to be passed
        required: false

      testautorepo:
        required: false
        type: string
      testautobranch:
        required: false
        type: string

    secrets:
      JENKINS_SECURITYTOKEN:
        required: true
      JENKINS_TOKEN:
        required: false

      GPR_READ_TOKEN:
        required: true
      GRADLE_PROPERTIES:
        required: true
      JFROG_USERNAME:
        required: true
      JFROG_EMAIL:
        required: true
      JFROG_PASSWORD:
        required: true
      JENKINSGENESIS_SONAR:
        required: true

      GHA_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fetch-aws-credentials:
    runs-on: [ appdev-selfhosted-al2023 ]
    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.set-creds.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.set-creds.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ steps.set-creds.outputs.AWS_SESSION_TOKEN }}

    env:
      SSM_PARAM_NAME: githubrunner-cddev-policy
      REGION: eu-west-2

    steps:

      - name: Install AWS CLI and jq
        run: |
          sudo dnf update -y
          sudo dnf install -y awscli jq
      - name: Fetch and Assume AWS Role
        id: set-creds
        run: |
          # Unset existing AWS credentials
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN
          # Fetch the AWS SSM parameter containing the role ARN
          aws_ssm_param_arn=$(aws ssm get-parameter --name $SSM_PARAM_NAME --region=$REGION --with-decryption --query "Parameter.Value")
          # Assume the IAM role using STS and extract the credentials
          aws_credentials_json=$(aws sts assume-role --role-arn ${aws_ssm_param_arn//\"/} --role-session-name githubActionSession --duration 3600 --region $REGION)
          # Extract credentials and output them for the next job
          AWS_ACCESS_KEY_ID=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.AccessKeyId)
          AWS_SECRET_ACCESS_KEY=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.SecretAccessKey)
          AWS_SESSION_TOKEN=$(echo "$aws_credentials_json" | jq --exit-status --raw-output .Credentials.SessionToken)
          # Set outputs for next jobs to use
          echo "::set-output name=AWS_ACCESS_KEY_ID::$AWS_ACCESS_KEY_ID"
          echo "::set-output name=AWS_SECRET_ACCESS_KEY::$AWS_SECRET_ACCESS_KEY"
          echo "::set-output name=AWS_SESSION_TOKEN::$AWS_SESSION_TOKEN"

  build:
    name: Steps to update sonar
    runs-on: appdev-small
    environment: master

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ inputs.branch }}

      - name: Print Input Values
        run: |
          echo "hostname: ${{ inputs.hostname }}"
          echo "genesis_user: ${{ inputs.genesis_user }}"

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://jenkinsdev.cdservice.genesis.global/buildByToken/buildWithParameters?token=${{ secrets.JENKINS_SECURITYTOKEN }}&job=AppDev-CI_CD/PLT_QA_Automation/sonar-update" \
            --data-urlencode "host_name=${{ inputs.HOSTNAME }}" \
            --data-urlencode "appuser=${{ inputs.appuser }}"




      - name: Install jq
        run: sudo dnf install -y jq

      - name: Poll Jenkins for Job Status
        run: |
          JOB_STATUS=""
          JOB_URL="https://jenkinsdev.cdservice.genesis.global/job/AppDev-CI_CD/job/PLT_QA_Automation/job/sonar-update/lastBuild/api/json"

          while [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; do
            RESPONSE=$(curl -s -u "purna.sakhamuri:${{ secrets.JENKINS_TOKEN }}" "$JOB_URL")
            JOB_STATUS=$(echo "$RESPONSE" | jq -r .result)
            echo "Current status: $JOB_STATUS"

            if [ "$JOB_STATUS" == "SUCCESS" ]; then
              echo "Jenkins job completed successfully."
              exit 0
            elif [ "$JOB_STATUS" == "FAILURE" ]; then
              echo "Jenkins job failed."
              exit 1
            elif [ "$JOB_STATUS" == "ABORTED" ]; then
              echo "Jenkins job was aborted."
              exit 2
            elif [ -z "$JOB_STATUS" ] || [ "$JOB_STATUS" == "null" ]; then
              echo "Job is still running..."
              sleep 10
            fi
          done

  build-generate-report-upload:
    runs-on: [ appdev-selfhosted-al2023 ]
    needs: [ fetch-aws-credentials,build ]

    env:
      REGION: eu-west-2
      AWS_ACCESS_KEY_ID: ${{ needs.fetch-aws-credentials.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ needs.fetch-aws-credentials.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ needs.fetch-aws-credentials.outputs.AWS_SESSION_TOKEN }}

    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: '0'
      #     ref: ${{ inputs.branch }}

      # - uses: actions/checkout@v3
      #   with:
      #     repository: ${{ inputs.testautorepo }}
      #     fetch-depth: '0'
      #     ref: ${{ inputs.testautobranch }}
      #     token: ${{ secrets.GHA_TOKEN }}

      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: ${{ inputs.java_version }}
      #     distribution: 'adopt'

      # - name: Configure Node
      #   if: ${{ !inputs.REGISTRY_URL  }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ inputs.node_version }}

      # - name: Configure Node if using JFROG npm packages
      #   if: ${{ inputs.REGISTRY_URL }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ inputs.node_version }}
      #     registry-url: ${{ inputs.REGISTRY_URL }}
      #     scope: ${{ inputs.SCOPE }}

      # - name: Restore gradle.properties and setup
      #   env:
      #     GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      #   working-directory: "${{ inputs.working-directory }}"
      #   shell: bash
      #   run: |
      #     mkdir -p ~/.gradle/
      #     echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
      #     echo "genesisArtifactoryUser=${{ secrets.JFROG_USERNAME }}" > ~/.gradle/gradle.properties
      #     echo "genesisArtifactoryPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties

      #     echo "systemProp.org.gradle.internal.http.connectionTimeout=180000" >> ~/.gradle/gradle.properties
      #     echo "systemProp.org.gradle.internal.http.socketTimeout=180000" >> ~/.gradle/gradle.properties

      #     echo "dockerUrl=genesisglobal-docker-internal.jfrog.io" >> ~/.gradle/gradle.properties
      #     echo "dockerUsername=${{ secrets.JFROG_USERNAME }}" >> ~/.gradle/gradle.properties
      #     echo "dockerPassword=${{ secrets.JFROG_PASSWORD }}" >> ~/.gradle/gradle.properties
      #     echo "dockerEmail=platformmanageteam@genesis.global" >> ~/.gradle/gradle.properties

      #     echo "genesis-home=../.genesis-home" >> ~/.gradle/gradle.properties
      #     echo "deploy-plugin-mode=local" >> ~/.gradle/gradle.properties
      #     sudo chmod +x ./gradlew
      #     sudo chmod +x ./${{ inputs.server-path }}/gradlew
      #     sudo chmod -R +rx ./${{ inputs.server-path }}/
      #     cat ~/.gradle/gradle.properties >>  ./gradle.properties
      #     if [ -z "${{ inputs.repo-name }}" ]; then
      #       echo "REPO_NAME=$(echo '${{ github.event.repository.name }}' | cut -d'-' -f1)" >> $GITHUB_ENV
      #     else
      #       echo "REPO_NAME=${{ inputs.repo-name }}" >> $GITHUB_ENV
      #     fi
      #     RELEASE_VERSION=$(echo "${{ inputs.version }}" | sed 's/\//-/g')
      #     echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      #     sed -E -i "s/^\s{4}version = \".+\"/    version = \"${RELEASE_VERSION}\"/g" ${{ inputs.server-path }}/build.gradle.kts

      - name: Download JaCoCo CLI
        run: |
          mkdir -p jacoco
          wget -O jacoco/jacoco.zip https://repo1.maven.org/maven2/org/jacoco/jacoco/0.8.12/jacoco-0.8.12.zip

          unzip jacoco/jacoco.zip -d jacoco || (echo "Unzip failed!" && exit 1)

          echo "Extracted files:"
          ls -l jacoco

      - name: Downloads
        run: |
          mkdir -p ${{ inputs.appuser }}
          cd ${{ inputs.appuser }}
          wget --user=${{ secrets.JFROG_USERNAME }} --password="${{secrets.JFROG_PASSWORD}}" https://genesisglobal.jfrog.io/artifactory/product/${{ inputs.appuser }}/server/genesis_${{ inputs.appuser }}_package-FahdTazi72-patch-3-qaautomation.tar.gz
          ls -al
          tar xf genesis_*.tar.gz
          rm genesis_*.tar.gz
          ls -al

      - name: Download JaCoCo exec file from S3
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
          aws configure set aws_session_token $AWS_SESSION_TOKEN --profile default
          aws configure set region $REGION --profile default

          aws s3 cp s3://genesis-cddev/qa-automation/jacoco/${{ inputs.appuser }}/jacoco.exec ./jacoco.exec
          ls -al jacoco.exec
          pwd

      - name: Generate JaCoCo XML Report (Manual)
        run: |
          cd ${{ inputs.appuser }}/${{ inputs.appuser }}/bin/
          java -jar ../../../jacoco/lib/jacococli.jar report ../../../jacoco.exec \
              --classfiles ./ \
              --html jacocoTestReport.html
              --xml jacocoTestReport.xml
          ls -al
          pwd


      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: /opt/actions-runner/_work/${{ inputs.appuser }}/${{ inputs.appuser }}/${{ inputs.appuser }}/${{ inputs.appuser }}/bin/jacocoTestReport.html



      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2.1.1
      #   env:
      #     SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
      #   with:
      #     projectBaseDir: ./${{ inputs.server-path }}
      #     args: >
      #       -Dsonar.organization=genesislcap
      #       -Dsonar.projectKey=genesislcap_fical
      #       -Dsonar.host.url=https://sonarcloud.io
      #       -Dsonar.java.binaries=/opt/actions-runner/_work/fical/fical/fical/fical/bin


      # - name: Server Build
      #   uses: gradle/gradle-build-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.JENKINSGENESIS_SONAR }}
      #   with:
      #     arguments: test jacocoTestReport sonarqube --no-configuration-cache -Dsonar.token=${{env.SONAR_TOKEN}}
      #     build-root-directory: ./${{ inputs.server-path }}
      #     cache-disabled: true