---
name: Lint

on:
  workflow_call:
    inputs:
      label:
        type: string
        required: true
        description: Name of workflow artifact that will contain build output
      ec2-instance-id:
        type: string
        required: true
        description: ID of ec2 instance that needs to be terminated

jobs:
  stop-runner:
    name: Stop self-hosted EC2 runner
    
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ec2runner_genesisglobal_key }}
          aws-secret-access-key: ${{ secrets.ec2runner_genesisglobal_secret }}
          aws-region: eu-west-2
          
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.ec2runner_ghtoken }}
          label: ${{ inputs.label }}
          ec2-instance-id: ${{ inputs.ec2-instance-id }}
